name: Build and Run Grunt Tasks

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # You can specify the required Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run Grunt tasks
      run: npx grunt

    - name: Start the application
      run: npm start
